spring:
  application:
    name: dwt
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
    url: jdbc:oracle:thin:@10.26.7.211:1521/dwt
    username: dwt
    password: dwt1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    clusters:
      account:
        bootstrap-servers: 10.26.7.104:9092,10.26.7.105:9092,10.26.7.106:9092
        topics:
          accountTopic: Information.Account.Test
      accountFu:
        bootstrap-servers: 10.26.7.104:9092,10.26.7.105:9092,10.26.7.106:9092
        topics:
          accountTopic: Information.AccountDeri.Test
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.fpts.fitint.controller
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    com.fpts.fitint: DEBUG

